#!/bin/sh
# THIS SCRIPT IS FOR AUTO INSTALL THE MODULE PLEASE USE TERMUX OR OTHER LINUX *Should be Work with apt thing in next update of this script
# THANKS TO WALANGKAJI (https://github.com/walangkaji) for the library
# Me for making it simple and android apk *hopefully done

# update and upgrade the termux
echo "Run apt update & upgrade"
apt update && apt upgrade -y

# installing php git and nano
echo "Installing the requirements"
apt install php git nano -y 

# git pull the repo 
echo "Clone the repo"
git clone https://github.com/Orangeskai/termux-f609 /data/data/com.termux/files/usr/etc/f609-serv --depth=1 --quiet

# give time for you debugging and make cleaner
echo "Waiting 10 second for debug"
sleep 10 && clear

# make the bin script !!!! REQUIRED
touch /data/data/com.termux/files/usr/bin/f609
chmod +x /data/data/com.termux/files/usr/bin/f609
tee -a /data/data/com.termux/files/usr/bin/f609 <<EOF > /dev/null
#!/bin/sh

# Help section
Help()
{
   # Display Help
   echo "Hi this is my the script maybe will help but idk this is still beta and im busy to fix it :)."
   echo 
   echo "For started the api server just type f609 and it automaticly started"
   echo "THIS SCRIPT MADE BY <3 by Orangeskai"
   echo 
   echo "Syntax: available [--help|--stop|--uninstall]"
   echo "options:"
   echo "--help          Print this Help."
   echo "--config	 open text editor and change your config like ip, user etc."
   echo "--uninstall     Delete all of this script from your system."
   echo "--remove	 Delete all the script but leave php still installed."
   echo
}

# Uninstall section
Uninstall()
{
  echo "Are you sure ?"
  echo "This will deleting php + script and this command"
  echo "Waiting 10 seconds"
  echo 
  echo "To cancel just pressed ctrl + c"
  echo
  sleep 10
  apt purge php -y
  rm -rf /data/data/com.termux/files/usr/etc/f609-serv
  rm -rf /data/data/com.termux/files/usr/bin/f609
  hash -r
}

# Uninstall section
Remove()
{
  echo "Are you sure ?"
  echo "This will deleting script and this command"
  echo "Php not going to UNINSTALL"
  echo "Waiting 10 seconds"
  echo 
  echo "To cancel just pressed ctrl + c"
  echo
  sleep 10
  rm -rf /data/data/com.termux/files/usr/etc/f609-serv
  rm -rf /data/data/com.termux/files/usr/bin/f609
  hash -r
}

# Config section
Config()
{
  echo "Ok please edit with your configuration !!!"
  sleep 5
  nano /data/data/com.termux/files/usr/etc/f609-serv/config.php
}

# Get the options
while [ "\$1" != "" ]; do
    case \$1 in
        --help )         Help
                         exit;;
	--config )	 Config
			 exit;;
        --uninstall )    Uninstall
                         exit;;
	--remove )	 Remove
			 exit;;
	-* | --*)	 Help
			 exit 1
    esac
    shift
done

# Main script !!!!
echo "For stopping the server just press ctrl + c"
php -S localhost:8809 -t /data/data/com.termux/files/usr/etc/f609-serv/Script

EOF

# tell to edit the config
printf "Please EDIT the config file\n"
printf "just type f609 --config :)\n"
echo
printf "Type f609 --help for more info\n"
echo
